name: VS Code Extension Release

on:
  push:
    tags:
      - 'vscode-v*.*.*'  # Trigger on vscode-v1.0.0 tags
  workflow_dispatch:      # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases and upload assets
      packages: read   # Required to read packages
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install extension dependencies
        run: |
          cd vscode-extension
          npm ci

      - name: Build extension
        run: |
          cd vscode-extension
          npm run build

      - name: Run tests
        run: |
          cd vscode-extension
          xvfb-run -a npm test

      - name: Package VSIX
        run: |
          cd vscode-extension
          npx vsce package --no-yarn

      - name: Upload VSIX to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: vscode-extension/*.vsix

      - name: Publish to VS Code Marketplace
        if: startsWith(github.ref, 'refs/tags/vscode-v')
        run: |
          cd vscode-extension
          npx vsce publish --no-yarn -p ${{ secrets.GLINCKER_VSCE_TOKEN }}

      - name: Create GitHub Release with VSIX
        if: startsWith(github.ref, 'refs/tags/vscode-v')
        uses: softprops/action-gh-release@v2
        with:
          name: "CommitWeave VS Code Extension ${{ github.ref_name }}"
          body: |
            ## CommitWeave VS Code Extension Release ${{ github.ref_name }}
            
            ### Features
            - **CommitWeave: Create Commit** - Interactive CLI integration
            - **CommitWeave: AI Commit** - AI-powered commit generation  
            - **CommitWeave: Configure** - Settings webview panel
            
            ### Installation
            1. Download the `.vsix` file from this release
            2. In VS Code: `View` → `Command Palette` → `Extensions: Install from VSIX...`
            3. Select the downloaded file
            
            Or install from the VS Code Marketplace: Search for "CommitWeave"
          files: vscode-extension/*.vsix
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}